---
title: "Running simulations"
author: "Hector Roux de Bézieux"
date: '`r format(Sys.time(), "%d %B , %Y")`'
output:
  pdf_document
---

```{r packages, include=F}
library(knitr)
opts_chunk$set(
  fig.pos = "!h", out.extra = "", warning = FALSE, message = FALSE,
  fig.width = 5, fig.align = "center", echo = TRUE
)
if (!"DailyHRB" %in% installed.packages()) {
  devtools::install_github("HectorRDB/DailyHRB")
}
libs <- c("here", "purrr", "DailyHRB")
suppressMessages(
  suppressWarnings(sapply(libs, require, character.only = TRUE))
)
rm(libs)
```

# Loading the data and the scripts.

```{r}
sample_data <- read.csv(here("data", "sample_ga_data_binomial_2019-04-26.csv"))
source(here("R", "sim_variables.R"))
source(here("R", "ga_gbm_function.R"))
# source(here("R", "vimshift_ph290_project.R"))
```

# Impact of n on results

```{r}
concordance <- function(l1, l2) {
  r1 <- sort(l1, decreasing = TRUE)
  r2 <- sort(l2, decreasing = TRUE)
  con <- map_dbl(1:length(l1), function(i) {
    sum(names(r1[1:i]) %in% names(r2[1:i]))}
  )
  return(sum(con))
}
results <- map_dbl(7:15, function(k) {
  n <- 2^k
  sim1 <- simulate_outcome(sample_data = sample_data, n = n, 
                           complexity = 1)
  trueOrder <- ranking_complex(ranking_info = sim1$ranking_info)
  gbOrder <- gbm(data = data.frame(sim1$covariates, y = sim1$y))
  
  return(concordance(trueOrder, gbOrder))
})

ggplot(data.frame(n = 2^(7:12), concordance = results),
       aes(x = n, y = results)) +
  geom_point() +
  my_theme() +
  scale_x_log10() +
  ggtitle("Concordance between the true variable importance ranking\nand the estimated ranling with other methods for various values of n")
```

# Impact of the complexity on results

```{r}
results <- map_dbl(0:10, function(i) {
  print(i)
  sim1 <- simulate_outcome(sample_data = sample_data, n = 1000, 
                           complexity = i)
  trueOrder <- ranking_complex(ranking_info = sim1$ranking_info)
  gbOrder <- gbm(data = data.frame(sim1$covariates, y = sim1$y))
  
  return(concordance(trueOrder, gbOrder))
})

ggplot(data.frame(complexity = 0:10, concordance = results),
       aes(x = complexity, y = results)) +
  geom_point() +
  my_theme() +
  ggtitle("Concordance between the true variable importance ranking\nand the estimated ranling with other methods for various values of complexity")
```

