---
title: "Simulation results analysis"
author: "Hector Roux de Bézieux"
date: '`r format(Sys.time(), "%d %B , %Y")`'
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r packages, include=F}
library(knitr)
opts_chunk$set(
  fig.pos = "!h", out.extra = "", warning = F, message = F,
  fig.width = 5, fig.align = "center", echo = F
)
libs <- c("here", "tidyverse")
suppressMessages(
  suppressWarnings(sapply(libs, require, character.only = TRUE))
)
rm(libs)
```

```{r}
gb_concordance <- function(truth, gb) {
  l1 <- names(sort(truth, decreasing = TRUE))
  l2 <- names(sort(gb, decreasing = TRUE))
  con <- map_dbl(1:length(l1), function(i) {
    sum(l1[1:i] %in% l2[1:i])}
  )
  return(sum(con))
}

tmleshift_concordance <- function(truth, vim) {
  l1 <- names(sort(truth, decreasing = TRUE))
  l2 <- vim$ordered_names
  con <- map_dbl(1:length(l1), function(i) {
    sum(l1[1:i] %in% l2[1:i])}
  )
  return(sum(con))
}
concordance <- function(rk) {
  map_dbl(1:27, function(i) {
    sum(rk[1:i] %in% 1:i)
  }) %>% sum %>% return()
}
```

```{r load data}
files <- list.files(here("data"))
complexity <- map_df(3:4, function(complexity) {
  files_c <- files[str_detect(files, paste0("complexity_", complexity))]
  names(files_c) <- 1:length(files_c)
  res <- map_df(files_c, function(file){
    complexity_c <- readRDS(here("data", file))
    return(c(gb_concordance(complexity_c$truth, complexity_c$gb),
             tmleshift_concordance(complexity_c$truth, complexity_c$vim)))
  }) %>% t() %>% as.data.frame()
  colnames(res) <- c("gbm", "tmleshift")
  res$complexity <- complexity
  return(res)  
})

ns <- map_df(8:11, function(k) {
  n <- 2^k
  files_n <- files[str_detect(files, as.character(n))]
  names(files_n) <- 1:length(files_n)
  res <- map_df(files_n, function(file){
    ns_n <- readRDS(here("data", file))
    return(c(gb_concordance(ns_n$truth, ns_n$gb),
             tmleshift_concordance(ns_n$truth, ns_n$vim)))
  }) %>% t() %>% as.data.frame()
  colnames(res) <- c("gbm", "tmleshift")
  res$n <- n
  return(res)  
})
```

```{r}
con_dist <- map_dbl(1:50000, function(rep) {
  concordance(sample(1:27, 27, replace = FALSE))
})
ggplot(data.frame(concordance = con_dist), aes(x = concordance)) +
  geom_histogram(bins = 300, aes(y = ..density..)) +
  geom_vline(xintercept = concordance(27:1), col = "red", size = 1, linetype = "dashed") +
  geom_vline(xintercept = concordance(1:27), col = "red", size = 1,  linetype = "dashed") +
  annotate("text", x = concordance(27:1) + 20, y = .05, label = "Minimum\nvalue") +
  annotate("text", x = concordance(1:27) - 20, y = .05, label = "Maximum\nvalue") +
  theme_classic()
ggsave("Figures/density_concordance.pdf")
```

```{r}
ns <- ns %>% gather(key = "method", value = "concordance", -n)
ggplot(ns, aes(x = n, y = concordance)) +
  geom_boxplot(aes(group = n)) +
  facet_wrap(~ method) +
  geom_point() +
  geom_hline(yintercept = 27^2 / 2, col = "red") +
  labs(x = "n") +
  scale_x_log10() +
  annotate("text", x = 800, y = 370, label = "Maximum value", col = "red")
  
ggsave("Figures/res_n.pdf")
```

```{r}
complexity <- complexity %>% gather(key = "method", value = "concordance", -complexity)
ggplot(complexity, aes(x = complexity, y = concordance)) +
  geom_boxplot(aes(group = complexity)) +
  facet_wrap(~ method) +
  geom_hline(yintercept = 27^2 / 2, col = "red") +
  labs(x = "complexity") +
  geom_point() +
  geom_hline(yintercept = 27^2 / 2, col = "red") +
  annotate("text", x = 3.5, y = 370, label = "Maximum value", col = "red")

ggsave("Figures/res_complexity.pdf")
```
